### ISSUE TITLE
OCAPI Reindex new feature

### ISSUE THREAD

**Issue by osapishchuk** [jenkinsci/osf-builder-suite-for-sfcc-data-import-plugin#2]
During the CI/CD process if we import new:
- Product
- Content
- Synonym
- Suggestion
- Inventory
data, it's required to reindex those data types to be able to fully to see the changes on the storefront. At this moment we need manually inform related stakeholders and reindex data on the instance under **_Merchant Tools >  Search >  Search Indexes_**.
It would be good to have this process as part of the plugin, which, for example, in the groovy configuration could have to reindex on/off and list of data types that require reindex.

**Comment by danechitoaie** [comment]
This was addressed by releasing a new plugin https://plugins.jenkins.io/osf-builder-suite-for-sfcc-run-job that allows you to run any custom SFCC job in Jenkins. So you can use that to run reindex, clear cache, etc.
