### ISSUE TITLE
Is it possible to use osf-builder for the pushing content and code to a newly created on demand sandbox?

### ISSUE THREAD

**Issue by lornadsilvasonos** [jenkinsci/osf-builder-suite-for-sfcc-data-import-plugin#3]
We are looking to automate our sandbox creation process with developers choosing what content and code they would like to see in the on demand sandbox.

**Comment by danechitoaie** [comment]
> Is it possible to use osf-builder for the pushing content and code to a newly created on demand sandbox?

Yes, you have two plugins https://plugins.jenkins.io/osf-builder-suite-for-sfcc-deploy/ for pushing code and https://plugins.jenkins.io/osf-builder-suite-for-sfcc-data-import/ for pushing metadata (content, etc.). These two plugins can be used from a Jenkins pipeline which allows you to script it in Groovy, or add params to the job. So you could have all metadata on Git but when setting up a sandbox you can chose what paths to ignore/or add to the build and only that will be used in the sandbox setup. So you can exclude/include only system object definitions, or a site data, etc.

For example look at this tutorial https://medium.com/@pradeep.sg406/jenkins-beginner-tutorial-how-to-parameterize-job-in-jenkins-110ee5c335c0 on how to setup a job with parameters and then once you have this you can use them as you wish and pass them to the deploy / data import plugins.

**Comment by lornadsilvasonos** [comment]
Thank you for your instant reply and the link. Since its a brand new sandbox, we do not have users on them. I am trying to use the plugin but OCAPI is giving me a 400 i.e bad request. I think the issue is more on the SFCC side of things.

**Comment by danechitoaie** [comment]
To use the plugin you do need to have the OCAPI settings configured first on the sandbox that would give the plugin access to it. So you would need to see if you can spin a sandbox with some default initial data (basically just the OCAPI settings needed) then the rest you can import with the plugin as needed from where you keep you metadata.

**Comment by lornadsilvasonos** [comment]
This make perfect sense. Thank you for your reply. I appreciate it.
