### ISSUE TITLE
Is it possible that DataPush takes webdav location as sourcePath?

### ISSUE THREAD

**Issue by milica-popovic-osf** [jenkinsci/osf-builder-suite-for-sfcc-data-import-plugin#4]
Is it possible that DataPush takes staging zip export as source. 
For example webdav location /webdav/Sites/Impex/src/instance/scheduled_export_for_jenkins-20210119144501.zip
It could allow import on sandbox directly from the staging backup.

Thanks

**Comment by danechitoaie** [comment]
The DataPush only pushes data. You can use additional steps in Jenkins that pulls the data from where you want. So you can combine with a NodeJS script, or some other plugin that pulls the data from wherever you have it.

In your case I think importing the data directly from your sandbox would be faster/better than "proxying" it trough Jenkins.
So maybe a NodeJS script that simulates a user going to BM -> Site import & Export -> And importing the archive directly from there would be better.
